language: c
# test
install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe"
- sudo apt-get update -q
- sudo apt-get install avrdude arduino

compiler:
- gcc
script: script/runtests.sh
before_install: script/bootstrap.sh
